config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :categories do
    resources :transactions
  end
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :transactions, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: :splash
  before_action :correct_user, only: %i[edit update destroy]

  def index
    @categories = Category.all
  end

  def show; end

  def new
    @category = current_user.categories.build
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_transactions_url(@category), notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  def correct_user
    @category = current_user.categories.find_by(id: params[:id])
    redirect_to categories_path, notice: 'Not authorized user' if @category.nil?
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon).merge(user_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  def index
    @category = Category.find_by_id(params[:category_id])
    @transactions = []
    @category_id = params[:category_id]
    join = Transaction.where(category_id: @category_id)
    transaction_ids = join.pluck(:id)
    transaction_ids.map do |id|
      @transactions << Transaction.find(id)
    end
    @transactions = @transactions.sort_by(&:created_at).reverse
  end

  def new
    @transaction = Transaction.new
  end

  def create
    category = Category.find_by_id(params[:category_id])
    @transaction = category.transactions.new(transaction_params)
    respond_to do |format|
      if @transaction.save
        format.html do
          redirect_to category_transactions_path(category.id), notice: 'Transaction was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
    end
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    # params.require(:transaction).permit(:name, :amount, :category_id).merge(user_id: current_user.id)
    params.require(:transaction).permit(:name, :amount, category_ids: []).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <%= image_tag(category.icon, :alt => "Category Icon") %>

  <p>
    <strong>Transactions:</strong>
    <%= category.transactions %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.text_field :name, placeholder: "Category name..", required: true %>
    <%= form.text_field :icon, placeholder: "Icon link..." %>
    <%= form.number_field :transactions, type: :hidden, value:0 %>

  <div class="submit">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="nav">
  <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %> 
    <%= image_tag 'logout.png' %>
  <% end %>
  <h1>BUDGET APP</h1>
  <%= image_tag 'hm.png' %>
</div>
<div class="title">
  <h2>Categories</h2>
</div>

<p style="color: green"><%= notice %></p>
<div id="categories">
  <% @categories.each do |category| %>
    <% if category.user == current_user %>
      <%= link_to category_transactions_path(category.id) do %>
        <div class="category">
          <%= image_tag(category.icon) %>
            <h2>
              <%= category.name %>
            </h2>
            <p>
              $ <%= category.transactions.sum(:amount) %>
            </p>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<section class="footer">
<%= link_to "NEW CATEGORY", new_category_path, class:"button" %>
</section>

app/views/categories/new.html.erb
<div class="nav">
  <%= link_to categories_path do %> 
    <%= image_tag 'back.png' %>
  <% end %>
  <h1>NEW CATEGORIES</h1>
  <%= image_tag 'hm.png' %>
</div>

<%= render "form", category: @category %>

<br>

app/views/home/index.html.erb
<section class="home">
    <h1 class="text-3xl font-bold text-text font-proxima">Budget App</h1>
    <div class="buttons">
      <%= link_to "Log In", new_user_session_path, class: "btn-main" %>
      <%= link_to "Register", new_user_registration_path, class: "btn-text" %>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
 
      <% if notice %>
       <p class="alert"><%= alert %></p>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/transactions/_form.html.erb
<%# <%= form_with(model: category_transaction_url(@category_id)) do |form| %> %>
<%= form_with(model: category_transaction_url(@category_id)) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder:"name..." %>
  </div>

  <div>
    <%= form.number_field :amount, placeholder:"amount" %>
  </div>


  <div>
    <%= form.number_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Name:</strong>
    <%= transaction.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= transaction.amount %>
  </p>

  <p>
    <strong>User:</strong>
    <%= transaction.user_id %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= transaction.category_id %>
  </p>

</div>

app/views/transactions/index.html.erb
<div class="nav">
   <%= link_to categories_path do %> 
    <%= image_tag 'back.png' %>
  <% end %>
  <h1>BUDGET APP</h1>
  <%= image_tag 'hm.png' %>
</div>

<p style="color: green"><%= notice %></p>
<div class="title">
  <h2><%= @category.name %></h2>
  <h2>$<%= @category.transactions.sum(:amount) %></h2>
</div>

<div id="categories">
  <% @transactions.each do |transaction| %>
    <div class="category">
        <h2><%= transaction.name %></h2>
        <p>$<%= transaction.amount %></p>
    </div>
  <% end %>
</div>

<section class="footer">
<%= link_to "New Transaction", new_category_transaction_path(@category_id), class:"button" %>
</section>

app/views/transactions/new.html.erb
<div class="nav">
  <%= link_to category_transactions_path do %> 
    <%= image_tag 'back.png' %>
  <% end %>
  <h1>NEW CATEGORIES</h1>
  <%= image_tag 'hm.png' %>
</div>

<%= form_for @transaction, url:  category_transactions_url  do |form| %>
  <% if @transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
 
      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
    <%= form.text_field :name, placeholder:"name...", required: true %>
    <%= form.number_field :amount, placeholder:"amount", required: true %>
    <%= form.collection_select(:category_id, current_user.categories, :id, :name, {}, { multiple: true, size: 4,  class: "input" }) %>
 
    <div class="submit">
      <%= form.submit %>
    </div>
  <% end %>

<br>